/**
 * Generates the service worker after the site is built.
 *
 * Rule T-2 says the whole site is cached on first visit — a crew with no bars
 * must be able to open the power line page. So the precache list is generated
 * from the actual build output rather than hand-maintained, because a
 * hand-maintained list is a list that is wrong.
 */
import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile, stat } from 'node:fs/promises';
import { join, relative, posix, sep } from 'node:path';

const DIST = process.env.DIST_DIR ?? 'dist';
const BASE = (process.env.BASE_PATH ?? '/').replace(/\/+$/, '') + '/';

/** Extensions worth holding offline. Everything the site is made of. */
const PRECACHE = new Set([
  '.html', '.css', '.js', '.json', '.webmanifest', '.woff2', '.svg', '.png',
  '.pdf', '.txt', '.wasm', '.pf_meta', '.pf_fragment', '.pf_index',
]);
/** Big or non-essential things that should be fetched on demand instead. */
const SKIP = [/\/sitemap[^/]*\.xml$/, /\/sw\.js$/];

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(full)));
    else out.push(full);
  }
  return out;
}

const files = await walk(DIST);
const urls = [];
let bytes = 0;

for (const f of files) {
  const rel = relative(DIST, f).split(sep).join(posix.sep);
  const ext = rel.slice(rel.lastIndexOf('.'));
  if (!PRECACHE.has(ext)) continue;
  const url = BASE + rel;
  if (SKIP.some((re) => re.test('/' + rel))) continue;
  // Directory-format pages: cache the clean URL, which is what links point at.
  urls.push(rel.endsWith('/index.html') ? url.slice(0, -'index.html'.length) : url);
  bytes += (await stat(f)).size;
}

urls.sort();

// The version is a hash of the precache list plus the content hash of the
// HTML, so a content-only edit still produces a new service worker.
const hash = createHash('sha256');
hash.update(urls.join('\n'));
for (const f of files.filter((x) => x.endsWith('.html')).sort()) hash.update(await readFile(f));
const version = hash.digest('hex').slice(0, 12);

const sw = `/* Kaua'i Saw School — offline cache. Generated by scripts/pwa.mjs. Do not edit. */
const VERSION = '${version}';
const CACHE = 'saw-' + VERSION;
const BASE = ${JSON.stringify(BASE)};
const OFFLINE = BASE + 'offline/';
const PRECACHE = ${JSON.stringify(urls)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      // One at a time in batches, and failures are tolerated: one 404 must not
      // stop the rest of the site from going offline-capable.
      const batch = 12;
      for (let i = 0; i < PRECACHE.length; i += batch) {
        await Promise.allSettled(
          PRECACHE.slice(i, i + batch).map((url) =>
            cache.add(new Request(url, { cache: 'reload' })),
          ),
        );
      }
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(keys.filter((k) => k !== CACHE && k.startsWith('saw-')).map((k) => caches.delete(k)));
      await self.clients.claim();
    })(),
  );
});

self.addEventListener('message', (event) => {
  if (event.data === 'skip-waiting') self.skipWaiting();
});

async function fromCacheThenNetwork(request, fallback) {
  const cache = await caches.open(CACHE);
  const hit = await cache.match(request, { ignoreSearch: request.mode === 'navigate' });
  if (hit) {
    // Refresh in the background so the next visit is current, but never make
    // the reader wait for the network.
    fetch(request)
      .then((res) => { if (res && res.ok && res.type === 'basic') cache.put(request, res.clone()); })
      .catch(() => {});
    return hit;
  }
  try {
    const res = await fetch(request);
    if (res && res.ok && res.type === 'basic') cache.put(request, res.clone());
    return res;
  } catch (err) {
    if (fallback) {
      const alt = await cache.match(fallback);
      if (alt) return alt;
    }
    throw err;
  }
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    event.respondWith(
      fromCacheThenNetwork(request, OFFLINE).catch(
        async () =>
          (await caches.match(OFFLINE)) ??
          new Response('Offline, and this page was not saved.', {
            status: 503,
            headers: { 'Content-Type': 'text/plain' },
          }),
      ),
    );
    return;
  }

  event.respondWith(fromCacheThenNetwork(request).catch(() => Response.error()));
});
`;

await writeFile(join(DIST, 'sw.js'), sw);
console.log(
  `sw.js: ${urls.length} files precached, ${(bytes / 1024).toFixed(0)} KB, version ${version}`,
);
